import Subreddits from 'components/Subreddits';

const list = [
  {
    category: 'NSFW',
    items: [
      {
        category: 'General',
        items: [
          '/r/nsfw',
          '/r/nsfw2',
          '/r/bonermaterial',
          '/r/nsfw411',
          '/r/iWantToFuckHer',
          '/r/exxxtras',
          '/r/distension',
          '/r/bimbofetish',
          '/r/christiangirls',
          '/r/dirtygaming',
          '/r/sexybutnotporn',
          '/r/femalepov',
          '/r/omgbeckylookathiscock',
          '/r/sexygirls',
          '/r/breedingmaterial',
          '/r/canthold',
          '/r/toocuteforporn',
          '/r/justhotwomen',
          '/r/stripgirls',
          '/r/hotstuffnsfw',
          '/r/uncommonposes',
          '/r/gifsofremoval',
          '/r/nostalgiafapping',
          '/r/truefmk',
          '/r/nudes',
          '/r/slut',
          '/r/lipsthatgrip',
        ],
      },
    ],
  },
  {
    category: 'Age',
    items: [
      {
        category: 'MILF',
        items: [
          '/r/milf',
          '/r/gonewild30plus',
          '/r/preggoporn',
          '/r/realmoms',
          '/r/agedbeauty',
          '/r/40plusgonewild',
          '/r/maturemilf',
        ],
      },
      {
        category: 'Teen',
        items: [
          '/r/legalteens',
          '/r/collegesluts',
          '/r/adorableporn',
          '/r/legalteensXXX',
          '/r/gonewild18',
          '/r/18_19',
          '/r/just18',
          '/r/PornStarletHQ',
          '/r/fauxbait',
          '/r/barelylegalteens',
        ],
      },
    ],
  },
  {
    category: 'Amateur',
    items: [
      {
        category: 'General',
        items: [
          '/r/realgirls',
          '/r/amateur',
          '/r/homemadexxx',
          '/r/dirtypenpals',
          '/r/FestivalSluts',
          '/r/CollegeAmateurs',
          '/r/amateurcumsluts',
          '/r/nsfw_amateurs',
          '/r/funwithfriends',
          '/r/randomsexiness',
          '/r/amateurporn',
          '/r/normalnudes',
          '/r/ItsAmateurHour',
          '/r/irlgirls',
          '/r/verifiedamateurs',
          '/r/NSFWverifiedamateurs',
        ],
      },
      {
        category: 'Cam',
        items: ['/r/Camwhores', '/r/camsluts', '/r/streamersgonewild'],
      },
      {
        category: 'Gonewild',
        items: [
          '/r/GoneWild',
          '/r/PetiteGoneWild',
          '/r/gonewildstories',
          '/r/GoneWildTube',
          '/r/treesgonewild',
          '/r/gonewildaudio',
          '/r/GWNerdy',
          '/r/gonemild',
          '/r/altgonewild',
          '/r/gifsgonewild',
          '/r/analgw',
          '/r/gonewildsmiles',
          '/r/onstageGW',
          '/r/RepressedGoneWild',
          '/r/bdsmgw',
          '/r/UnderwearGW',
          '/r/LabiaGW',
          '/r/TributeMe',
          '/r/WeddingsGoneWild',
          '/r/gwpublic',
          '/r/assholegonewild',
          '/r/leggingsgonewild',
          '/r/dykesgonewild',
          '/r/goneerotic',
          '/r/snapchatgw',
          '/r/gonewildhairy',
          '/r/gonewildtrans',
          '/r/gonwild',
          '/r/ratemynudebody',
        ],
      },
      {
        category: 'Age',
        items: [
          '/r/gonewild30plus',
          '/r/gonewild18',
          '/r/onmww (formerly /r/ohnomomwentwild)',
          '/r/40plusgonewild',
        ],
      },
      {
        category: 'Couples',
        items: [
          '/r/GWCouples',
          '/r/gonewildcouples',
          '/r/gwcumsluts',
          '/r/WouldYouFuckMyWife',
          '/r/couplesgonewild',
        ],
      },
      {
        category: 'Curves',
        items: [
          '/r/gonewildcurvy',
          '/r/GoneWildplus',
          '/r/BigBoobsGW',
          '/r/bigboobsgonewild',
          '/r/mycleavage',
          '/r/gonewildchubby',
        ],
      },
      {
        category: 'Ethnicity',
        items: [
          '/r/AsiansGoneWild',
          '/r/gonewildcolor',
          '/r/indiansgonewild',
          '/r/latinasgw',
          '/r/pawgtastic',
        ],
      },
      {
        category: 'Occupation',
        items: ['/r/workgonewild', '/r/GoneWildScrubs', '/r/swingersgw', '/r/militarygonewild'],
      },
      {
        category: 'Snapchat',
        items: ['/r/NSFW_Snapchat', '/r/snapchat_sluts', '/r/snapleaks'],
      },
      {
        category: 'Wives',
        items: [
          '/r/wifesharing',
          '/r/hotwife',
          '/r/wouldyoufuckmywife',
          '/r/slutwife',
          '/r/naughtywives',
        ],
      },
    ],
  },
  {
    category: 'Animated',
    items: [
      {
        category: 'General',
        items: [
          '/r/rule34',
          '/r/ecchi',
          '/r/futanari',
          '/r/doujinshi',
          '/r/yiff',
          '/r/furry',
          '/r/monstergirl',
        ],
      },
      {
        category: 'Comics',
        items: ['/r/rule34_comics', '/r/sex_comics'],
      },
      {
        category: 'Hentai',
        items: [
          '/r/hentai',
          '/r/hentai_gif',
          '/r/WesternHentai',
          '/r/hentai_irl',
          '/r/traphentai',
          '/r/hentaibondage',
        ],
      },
      {
        category: 'Video games',
        items: [
          '/r/overwatch_porn',
          '/r/pokeporn',
          '/r/bowsette',
          '/r/rule34lol',
          '/r/rule34overwatch',
        ],
      },
    ],
  },
  {
    category: 'BDSM',
    items: ['/r/BDSM', '/r/Bondage', '/r/BDSMcommunity', '/r/bdsmgw', '/r/femdom'],
  },
  {
    category: 'Blowjobs',
    items: [
      '/r/blowjobs',
      '/r/deepthroat',
      '/r/onherknees',
      '/r/blowjobsandwich',
      '/r/iwanttosuckcock',
    ],
  },
  {
    category: 'Body parts',
    items: [
      {
        category: 'Ass',
        items: [
          '/r/ass',
          '/r/asstastic',
          '/r/facedownassup',
          '/r/assinthong',
          '/r/bigasses',
          '/r/buttplug',
          '/r/TheUnderbun',
          '/r/booty',
          '/r/pawg',
          '/r/paag',
          '/r/cutelittlebutts',
          '/r/hipcleavage',
          '/r/frogbutt',
          '/r/HungryButts',
          '/r/cottontails',
          '/r/lovetowatchyouleave',
          '/r/celebritybutts',
          '/r/cosplaybutts',
          '/r/whooties',
          '/r/booty_queens',
          '/r/twerking',
        ],
      },
      {
        category: 'Anal',
        items: ['/r/anal', '/r/analgw', '/r/painal', '/r/masterofanal', '/r/buttsharpies'],
      },
      {
        category: 'Asshole',
        items: [
          '/r/asshole',
          '/r/AssholeBehindThong',
          '/r/assholegonewild',
          '/r/spreadem',
          '/r/godasshole',
        ],
      },
      {
        category: 'Boobs',
        items: [
          '/r/boobies',
          '/r/TittyDrop',
          '/r/boltedontits',
          '/r/boobbounce',
          '/r/boobs',
          '/r/downblouse',
          '/r/homegrowntits',
          '/r/cleavage',
          '/r/breastenvy',
          '/r/youtubetitties',
          '/r/torpedotits',
          '/r/thehangingboobs',
          '/r/page3glamour',
          '/r/fortyfivefiftyfive',
          '/r/tits',
          '/r/amazingtits',
          '/r/titstouchingtits',
        ],
      },
      {
        category: 'Busty',
        items: [
          '/r/BustyPetite',
          '/r/hugeboobs',
          '/r/stacked',
          '/r/burstingout',
          '/r/BigBoobsGW',
          '/r/bigboobsgonewild',
          '/r/2busty2hide',
          '/r/bigtiddygothgf',
          '/r/engorgedveinybreasts',
          '/r/bigtitsinbikinis',
          '/r/biggerthanherhead',
        ],
      },
      {
        category: 'Nipples',
        items: ['/r/pokies', '/r/ghostnipples', '/r/nipples', '/r/puffies', '/r/lactation'],
      },
      {
        category: 'Small',
        items: ['/r/tinytits', '/r/aa_cups'],
      },
      {
        category: 'Titfuck',
        items: ['/r/titfuck', '/r/clothedtitfuck'],
      },
      {
        category: 'Face',
        items: ['/r/braceface'],
      },
      {
        category: 'Hair',
        items: ['/r/GirlswithNeonHair', '/r/shorthairchicks', '/r/blonde'],
      },
      {
        category: 'Legs',
        items: ['/r/girlsinyogapants', '/r/stockings', '/r/legs', '/r/tightshorts'],
      },
      {
        category: 'Feet',
        items: ['/r/buttsandbarefeet', '/r/feet'],
      },
      {
        category: 'Thighs',
        items: ['/r/datgap', '/r/thighhighs', '/r/thickthighs', '/r/thighdeology'],
      },
      {
        category: 'Pussy',
        items: [
          '/r/pussy',
          '/r/rearpussy',
          '/r/innie',
          '/r/simps',
          '/r/pelfie',
          '/r/LabiaGW',
          '/r/godpussy',
          '/r/presenting',
          '/r/cameltoe',
          '/r/hairypussy',
          '/r/pantiestotheside',
          '/r/breakingtheseal',
          '/r/moundofvenus',
          '/r/pussymound',
        ],
      },
      {
        category: 'Skin',
        items: [
          '/r/Hotchickswithtattoos',
          '/r/sexyfrex',
          '/r/tanlines',
          '/r/oilporn',
          '/r/ComplexionExcellence',
        ],
      },
      {
        category: 'Waist',
        items: ['/r/SexyTummies', '/r/theratio'],
      },
    ],
  },
  {
    category: 'Body types',
    items: [
      {
        category: 'Bodies',
        items: ['/r/bodyperfection', '/r/samespecies', '/r/athleticgirls', '/r/coltish'],
      },
      {
        category: 'Thick',
        items: [
          '/r/gonewildcurvy',
          '/r/curvy',
          '/r/gonewildplus',
          '/r/thick',
          '/r/juicyasians',
          '/r/voluptuous',
          '/r/biggerthanyouthought',
          '/r/jigglefuck',
          '/r/chubby',
          '/r/SlimThick',
          '/r/massivetitsnass',
          '/r/thicker',
          '/r/thickthighs',
          '/r/tightsqueeze',
          '/r/casualjiggles',
          '/r/bbw',
          '/r/gonewildchubby',
          '/r/amazingcurves',
        ],
      },
      {
        category: 'Athletic',
        items: ['/r/fitgirls', '/r/fitnakedgirls', '/r/volleyballgirls', '/r/Ohlympics'],
      },
      {
        category: 'Petite',
        items: [
          '/r/BustyPetite',
          '/r/dirtysmall',
          '/r/petitegonewild /r/xsmallgirls',
          '/r/funsized',
          '/r/hugedicktinychick',
          '/r/petite',
          '/r/skinnytail',
        ],
      },
    ],
  },
  {
    category: 'Celebrity',
    items: [
      '/r/celebnsfw',
      '/r/WatchItForThePlot',
      '/r/nsfwcelebarchive /r/celebritypussy',
      '/r/oldschoolcoolNSFW',
      '/r/extramile',
      '/r/jerkofftocelebs',
      '/r/celebritybutts',
      '/r/onoffcelebs',
      '/r/celebswithbigtits',
      '/r/youtubersgonewild',
    ],
  },
  {
    category: 'Cum',
    items: [
      '/r/cumsluts',
      '/r/GirlsFinishingTheJob',
      '/r/cumfetish',
      '/r/amateurcumsluts',
      '/r/cumcoveredfucking',
      '/r/cumhaters',
      '/r/thickloads',
      '/r/before_after_cumsluts',
      '/r/pulsatingcumshots',
      '/r/impressedbycum',
      '/r/creampies',
      '/r/throatpies',
      '/r/FacialFun',
      '/r/cumonclothes',
      '/r/oralcreampie',
      '/r/creampie',
    ],
  },
  {
    category: 'Emotions',
    items: ['/r/HappyEmbarrassedGirls', '/r/unashamed', '/r/borednignored', '/r/annoyedtobenude'],
  },
  {
    category: 'Ethnicity',
    items: [
      {
        category: 'Asian',
        items: [
          '/r/AsianHotties',
          '/r/AsiansGoneWild',
          '/r/realasians',
          '/r/juicyasians',
          '/r/AsianNSFW',
          '/r/nextdoorasians',
          '/r/asianporn',
          '/r/bustyasians',
          '/r/paag',
        ],
      },
      {
        category: 'Indian',
        items: ['/r/IndianBabes', '/r/indiansgonewild'],
      },
      {
        category: 'Japanese',
        items: ['/r/NSFW_Japan', '/r/javdownloadcenter'],
      },
      {
        category: 'Korean',
        items: ['/r/kpopfap', '/r/NSFW_Korea'],
      },
      {
        category: 'Ebony',
        items: [
          '/r/WomenOfColor',
          '/r/darkangels',
          '/r/blackchickswhitedicks',
          '/r/ebony',
          '/r/Afrodisiac',
        ],
      },
      {
        category: 'Ginger',
        items: ['/r/ginger', '/r/redheads'],
      },
      {
        category: 'Latina',
        items: ['/r/latinas', '/r/latinasgw', '/r/latinacuties'],
      },
      {
        category: 'White',
        items: ['/r/palegirls', '/r/pawg', '/r/snowwhites', '/r/whooties'],
      },
    ],
  },
  {
    category: 'GIFs',
    items: [
      '/r/NSFW_GIF',
      '/r/nsfw_gifs',
      '/r/porn_gifs',
      '/r/porninfifteenseconds',
      '/r/CuteModeSlutMode',
      '/r/60fpsporn',
      '/r/NSFW_HTML5',
      '/r/the_best_nsfw_gifs',
      '/r/verticalgifs',
      '/r/besthqporngifs',
    ],
  },
  {
    category: 'Groups',
    items: ['/r/twingirls', '/r/groupofnudegirls', '/r/Ifyouhadtopickone'],
  },
  {
    category: 'Hardcore',
    items: [
      '/r/nsfwhardcore',
      '/r/SheLikesItRough',
      '/r/strugglefucking',
      '/r/jigglefuck',
      '/r/whenitgoesin',
      '/r/outercourse',
      '/r/gangbang',
      '/r/pegging',
      '/r/insertions',
      '/r/passionx',
      '/r/xsome',
      '/r/shefuckshim',
      '/r/cuckold',
      '/r/cuckquean',
      '/r/breeding',
      '/r/forcedcreampie',
      '/r/hugedicktinychick',
      '/r/amateurgirlsbigcocks',
      '/r/bbcsluts',
      '/r/facesitting',
      '/r/nsfw_plowcam',
      '/r/pronebone',
      '/r/facefuck',
      '/r/girlswhoride',
    ],
  },
  {
    category: 'High quality',
    items: ['/r/60fpsporn', '/r/highresNSFW', '/r/NSFW_HTML5'],
  },
  {
    category: 'Incest',
    items: ['/r/incestporn', '/r/wincest', '/r/incest_gifs'],
  },
  {
    category: 'Individuals',
    items: [
      {
        category: 'Professionals',
        items: [
          '/r/remylacroix',
          '/r/Anjelica_Ebbi',
          '/r/BlancNoir',
          '/r/rileyreid',
          '/r/tessafowler',
          '/r/lilyivy',
          '/r/mycherrycrush',
          '/r/gillianbarnes',
          '/r/emilybloom',
          '/r/miamalkova',
          '/r/sashagrey',
          '/r/angelawhite',
          '/r/miakhalifa',
          '/r/alexapearl',
          '/r/missalice_18',
          '/r/lanarhoades',
          '/r/evalovia',
          '/r/GiannaMichaels',
          '/r/erinashford',
          '/r/sextrophies',
          '/r/sabrina_nichole',
          '/r/LiyaSilver',
          '/r/MelissaDebling',
          '/r/AdrianaChechik',
          '/r/abelladanger',
        ],
      },
      {
        category: 'Redditors',
        items: [
          '/r/sarah_xxx',
          '/r/dollywinks',
          '/r/funsizedasian',
          '/r/Kawaiiikitten',
          '/r/legendarylootz',
          '/r/sexyflowerwater',
          '/r/keriberry_420',
          '/r/justpeachyy',
          '/r/hopelesssofrantic',
        ],
      },
    ],
  },
  {
    category: 'Lesbian',
    items: [
      '/r/lesbians',
      '/r/StraightGirlsPlaying',
      '/r/girlskissing',
      '/r/mmgirls',
      '/r/dykesgonewild',
      '/r/justfriendshavingfun',
    ],
  },
  {
    category: 'Masturbation/Orgasm',
    items: [
      '/r/holdthemoan',
      '/r/O_faces',
      '/r/jilling',
      '/r/gettingherselfoff',
      '/r/quiver',
      '/r/GirlsHumpingThings',
      '/r/forcedorgasms',
      '/r/mmgirls',
      '/r/ruinedorgasms',
      '/r/realahegao',
      '/r/suctiondildos',
      '/r/baddragon',
      '/r/grool',
      '/r/squirting',
    ],
  },
  {
    category: 'Men',
    items: [
      '/r/ladybonersgw',
      '/r/massivecock',
      '/r/chickflixxx',
      '/r/gaybrosgonewild',
      '/r/sissies',
      '/r/penis',
      '/r/monsterdicks',
      '/r/thickdick',
    ],
  },
  {
    category: 'Misogyny',
    items: ['/r/freeuse', '/r/fuckdoll', '/r/degradingholes', '/r/fuckmeat'],
  },
  {
    category: 'Outfits',
    items: [
      {
        category: 'General',
        items: [
          '/r/OnOff',
          '/r/nsfwoutfits',
          '/r/girlswithglasses',
          '/r/collared',
          '/r/seethru',
          '/r/sweatermeat',
          '/r/cfnm',
          '/r/nsfwfashion',
          '/r/leotards',
          '/r/whyevenwearanything',
          '/r/shinyporn',
          '/r/gothsluts',
        ],
      },
      {
        category: 'Bikinis',
        items: ['/r/bikinis', '/r/bikinibridge', '/r/bigtitsinbikinis'],
      },
      {
        category: 'Costumes',
        items: ['/r/nsfwcosplay', '/r/nsfwcostumes', '/r/girlsinschooluniforms'],
      },
      {
        category: 'Dresses/Skirts',
        items: ['/r/WtSSTaDaMiT', '/r/tightdresses', '/r/upskirt', '/r/SchoolgirlSkirts'],
      },
      {
        category: 'Stockings/Socks',
        items: ['/r/stockings', '/r/thighhighs', '/r/leggingsgonewild'],
      },
      {
        category: 'Pants/Shorts',
        items: ['/r/Bottomless_Vixens', '/r/tightshorts', '/r/tight_shorts'],
      },
      {
        category: 'Yoga pants',
        items: ['/r/girlsinyogapants', '/r/yogapants'],
      },
      {
        category: 'Underwear',
        items: ['/r/lingerie', '/r/pantiestotheside'],
      },
      {
        category: 'Thongs',
        items: ['/r/assinthong', '/r/AssholeBehindThong'],
      },
    ],
  },
  {
    category: 'Professional',
    items: ['/r/porn', '/r/suicidegirls', '/r/GirlsDoPorn ', '/r/pornstarhq', '/r/porninaminute'],
  },
  {
    category: 'Public',
    items: [
      '/r/ChangingRooms',
      '/r/workgonewild',
      '/r/FlashingGirls',
      '/r/publicflashing',
      '/r/sexinfrontofothers',
      '/r/NotSafeForNature',
      '/r/gwpublic',
      '/r/realpublicnudity',
      '/r/flashingandflaunting',
      '/r/publicsexporn',
      '/r/nakedadventures',
    ],
  },
  {
    category: 'Social media',
    items: [
      '/r/socialmediasluts',
      '/r/slutsofsnapchat',
      '/r/OnlyFans101',
      '/r/tiktoknsfw',
      '/r/tiktokthots',
      '/r/tiktokporn',
    ],
  },
  {
    category: 'Trash',
    items: ['/r/trashyboners', '/r/flubtrash'],
  },
  {
    category: 'Selfies',
    items: ['/r/realsexyselfies', '/r/nude_selfie'],
  },
  {
    category: 'Trans',
    items: [
      '/r/Tgirls',
      '/r/traps',
      '/r/futanari',
      '/r/gonewildtrans',
      '/r/tgifs',
      '/r/shemales',
      '/r/femboys',
      '/r/transporn',
    ],
  },
  {
    category: 'Videos',
    items: ['/r/pornvids', '/r/nsfw_videos'],
  },
  {
    category: 'Looking for',
    items: ['/r/TipOfMyPenis', '/r/pornID'],
  },
  {
    category: 'Other',
    items: [
      '/r/randomactsofblowjob',
      '/r/NSFWFunny',
      '/r/pornhubcomments',
      '/r/confusedboners',
      '/r/dirtykikpals',
      '/r/nsfw_wtf',
      '/r/randomactsofmuffdive',
      '/r/stupidslutsclub',
      '/r/sluttyconfessions',
      '/r/jobuds',
      '/r/drunkdrunkenporn',
    ],
  },
];

export default function ListPage() {
  return <Subreddits list={list} />;
}
